# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://ecila.github.io/HAL/
title: HAL
#email: 
author: Alice Eldridge
description: > # "Humanising Algorithmic Listening. An AHRC network aiming to imagine the future of machine listening in the arts and humanities"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/algolisten
  - title: soundcloud
    url: https://soundcloud.com
# ----------------------- #
#     - title: github
#    url: https://github.com/ecila/HAL
# ----------------------- #


